# Generated by Django 4.2.6 on 2023-10-25 23:35

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('c980e848-0f91-4300-8bc9-ed579ef15c97'), primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name_plural': 'turma',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('5ee337bb-d724-4eb6-b575-810f1a64845b'), primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('cf52e1ff-fd28-483d-8698-cd1c8b1a70f2'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('registration_number', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'verbose_name_plural': 'professor',
            },
        ),
        migrations.CreateModel(
            name='UniversityClass',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('5620e34c-8560-4e03-a851-fddfc32e50d1'), editable=False, primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField()),
                ('final', models.DateTimeField()),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universityclasses', to='app.classroom')),
            ],
            options={
                'verbose_name_plural': 'aula',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('1b6f7f95-037f-4b7f-9d96-57e5b053fbd9'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('registration_number', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('24c1ab1d-dfc7-48e7-8018-6bae5673c087'), editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5, message='O valor deve ser menor ou igual a 5.'), django.core.validators.MinValueValidator(1, message='O valor deve ser maior ou igual a 1.')])),
                ('feedback', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 10, 25, 23, 35, 40, 408283), editable=False)),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.student')),
                ('universityclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.universityclass')),
            ],
            options={
                'verbose_name_plural': 'avaliações',
            },
        ),
        migrations.CreateModel(
            name='ClassroomStudent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('388afe0a-8713-4701-8abb-2b11e19126c1'), primary_key=True, serialize=False)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classroom')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='app.student')),
            ],
            options={
                'verbose_name_plural': 'atribuir turma ao aluno',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.teacher'),
        ),
    ]
